version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "/wait && node index.js"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
      build:
        context: nginx
      container_name: nginx
      tty: true
      ports:
        - "8080:80"
      networks:
        - node-network
      depends_on:
        - app

networks:
  node-network:
    driver: "bridge"